---

- name: Install PostgreSQL
  yum:
    name:
    - postgresql
    - postgresql-contrib
    - postgresql-server
    - python3-psycopg2
    - python-psycopg2
    state: present
    #become: yes
  tags:
  - django
  - django::postgresql

- name: initialize the database cluster
  #command: export PGDATA=/var/lib/pgsql/data
  command: postgresql-setup initdb
  when:  not 'Data directory is not empty!'
  #ignore_errors: yes
  tags:
  - django
  - django::postgresql


- name: Start and enable postgres
  service:
    name: postgresql
    enabled: yes
    state: started
  tags:
  - django
  - django::postgresql


- name: Create database
  postgresql_db:
    name: "{{ postgressql.db_name }}"
    state: present
  become: yes
  become_user: postgres
  tags:
  - django
  - django::postgresql


- name: Create user
  postgresql_user: db="{{ postgressql.db_name }}"
                   name="{{ postgressql.db_user }}"
                   password="{{ postgressql.db_password }}"
                   priv='ALL'
                   state=present
                   role_attr_flags=NOSUPERUSER,NOCREATEDB
  become: yes
  become_user: postgres

  tags:
  - django
  - django::postgresql
#после всего необходимо настроить подключение пользователя
# я настроил метод trust для пользователя gbuser с локальным подключением через сокет
#local	all		gbuser					trust