---

- name: Update nginx config
  block:
    - name: create directory for nginx files
      file:
        path: "{{ nginx.root_dir }}"
        state: directory
        mode: 0755
        owner: root
        group: root
      become: yes
    - name: update nginx config
      template:
        src: nginx.conf.j2
        dest: /etc/nginx/nginx.conf
        owner: nginx
      notify:
        - reload nginx
      become: yes
      tags:
      - nginx
      - nginx::config




