---
- name: Install Gunicorn
  pip:
     name: gunicorn
     virtualenv: "{{ django.project_name_path }}/env"
     virtualenv_command: virtualenv
     virtualenv_python: python3
  tags:
  - django
  - django::gunicorn

- name: Create Gunicorn Socket file
  template:
    src: gunicorn.socket.j2
    dest: /etc/systemd/system/gunicorn.socket
  tags:
  - django
  - django::gunicorn

- name: Create Gunicorn Service file
  template:
    src: gunicorn.service.j2
    dest: /etc/systemd/system/gunicorn.service
  tags:
  - django
  - django::gunicorn
- name: Start Gunicorn.socket
  shell: "/bin/systemctl start gunicorn.socket"
  tags:
  - django
  - django::gunicorn

- name: Enable Gunicorn.socket
  shell: "/bin/systemctl enable gunicorn.socket"
  tags:
  - django
  - django::gunicorn